import { HiOutlineSortDescending } from 'react-icons/hi';
import { MdOutlineEmail, MdOutlineMarkEmailRead, MdOutlineMarkEmailUnread } from 'react-icons/md';
import { BsCircle, BsCircleFill, BsCircleHalf } from 'react-icons/bs';
import { AiFillFileExcel, AiFillFilePdf, AiFillFileText, AiFillFileWord, AiFillFileZip } from 'react-icons/ai';
import {
  LuAlertOctagon,
  LuAlertTriangle,
  LuArrowDown,
  LuArrowDownUp,
  LuArrowDownWideNarrow,
  LuArrowLeft,
  LuArrowRight,
  LuArrowUp,
  LuArrowUpNarrowWide,
  LuBell,
  LuBriefcase,
  LuBuilding,
  LuBuilding2,
  LuCalculator,
  LuCalendarDays,
  LuCaseSensitive,
  LuCheck,
  LuCheckCircle,
  LuCheckCircle2,
  LuChevronDown,
  LuChevronFirst,
  LuChevronLast,
  LuChevronLeft,
  LuChevronRight,
  LuClipboardCheck,
  LuClipboardCopy,
  LuCopyright,
  LuDownload,
  LuExternalLink,
  LuFile,
  LuFileBadge,
  LuFileClock,
  LuFileSearch,
  LuFileSymlink,
  LuFilter,
  LuFilterX,
  LuFolder,
  LuFolderOpen,
  LuGavel,
  LuHelpCircle,
  LuHome,
  LuInbox,
  LuInfo,
  LuKeyboard,
  LuKeyRound,
  LuLink,
  LuLock,
  LuLogIn,
  LuLogOut,
  LuMenu,
  LuMinus,
  LuMoonStar,
  LuMoreVertical,
  LuPalette,
  LuPanelLeftClose,
  LuPanelLeftOpen,
  LuPaperclip,
  LuPenSquare,
  LuPhone,
  LuPlayCircle,
  LuPlus,
  LuPlusCircle,
  LuRefreshCw,
  LuRotateCcw,
  LuSave,
  LuSearch,
  LuSendHorizonal,
  LuSettings,
  LuShield,
  LuSun,
  LuTrash2,
  LuType,
  LuUndo2,
  LuUnlock,
  LuUpload,
  LuUser,
  LuUserCheck,
  LuUserCog,
  LuUserMinus,
  LuUserPlus,
  LuUsers,
  LuUserX,
  LuX,
  LuXCircle,
} from 'react-icons/lu';
import { TbUserEdit } from 'react-icons/tb';
import { HiOutlineIdentification } from 'react-icons/hi2';
import { FaFileCsv } from 'react-icons/fa';

export const ThemeIcons = {
  User: LuUser,
  Users: LuUsers,
  UserPlus: LuUserPlus,
  UserMinus: LuUserMinus,
  UserX: LuUserX,
  UserCheck: LuUserCheck,
  UserEdit: TbUserEdit,
  UserCog: LuUserCog,
  IdCard: HiOutlineIdentification,

  Link: LuLink,
  ExternalLink: LuExternalLink,

  LegalEntity: LuBuilding2,
  Certificate: LuFileBadge,
  FileClock: LuFileClock,
  Restart: LuRotateCcw,
  Calculator: LuCalculator,
  Gavel: LuGavel,
  Building: LuBuilding,
  Building2: LuBuilding2,
  Briefcase: LuBriefcase,

  Key: LuKeyRound,
  Keyboard: LuKeyboard,
  Clipboard: LuClipboardCopy,
  ClipboardChecked: LuClipboardCheck,

  File: LuFile,
  Folder: LuFolder,
  FolderOpen: LuFolderOpen,

  Title: LuType,
  Text: LuCaseSensitive,

  Home: LuHome,

  Add: LuPlusCircle,
  Edit: LuPenSquare,
  Save: LuSave,
  Delete: LuTrash2,
  View: LuFileSearch,

  Shield: LuShield,

  Logout: LuLogOut,
  Login: LuLogIn,

  Notification: LuBell,
  Settings: LuSettings,
  Project: LuFile,

  Mail: MdOutlineEmail,
  MailRead: MdOutlineMarkEmailRead,
  MailUnread: MdOutlineMarkEmailUnread,

  Phone: LuPhone,

  Info: LuInfo,
  Question: LuHelpCircle,

  Refresh: LuRefreshCw,
  Undo: LuUndo2,
  Search: LuSearch,
  Filter: LuFilter,
  NoFilter: LuFilterX,

  ArrowLeft: LuArrowLeft,
  ArrowRight: LuArrowRight,
  ArrowUp: LuArrowUp,
  ArrowDown: LuArrowDown,

  Accept: LuCheckCircle2,
  Reject: LuXCircle,

  Menu: LuMenu,
  Close: LuX,
  Dropdown: LuChevronDown,
  Checked: LuCheck,
  TripleDots: LuMoreVertical,

  // chevron
  Calendar: LuCalendarDays,

  Copyright: LuCopyright,

  Warning: LuAlertTriangle,
  Error: LuAlertOctagon,
  Success: LuCheckCircle,

  Plus: LuPlus,
  Minus: LuMinus,

  Download: LuDownload,
  FilePreview: LuFileSymlink,
  Upload: LuUpload,
  Attach: LuPaperclip,
  FileExcel: AiFillFileExcel,
  FileCsv: FaFileCsv,
  FilePdf: AiFillFilePdf,
  FileText: AiFillFileText,
  FileWord: AiFillFileWord,
  FileZip: AiFillFileZip,

  SortUp: LuArrowUpNarrowWide,
  SortDown: LuArrowDownWideNarrow,
  Unsorted: LuArrowDownUp,
  Sort: HiOutlineSortDescending,

  PageNext: LuChevronRight,
  PagePrev: LuChevronLeft,
  PageFirst: LuChevronFirst,
  PageLast: LuChevronLast,

  PanelOpen: LuPanelLeftOpen,
  PanelClose: LuPanelLeftClose,

  Empty: LuInbox,

  Light: LuSun,
  Dark: LuMoonStar,

  StatusCompleted: BsCircleFill,
  StatusInProgress: BsCircleHalf,
  StatusNotStarted: BsCircle,

  Send: LuSendHorizonal,
  Lock: LuLock,
  Unlock: LuUnlock,

  Start: LuPlayCircle,

  Palette: LuPalette,

  // Quill
  // Bold: LuBold,
  // Italic: LuItalic,
  // Underline: LuUnderline,
  // Strike: LuStrikethrough,
  // List: LuListOrdered,
  // BulletList: LuList,
  // Indent: LuIndent,
  // Outdent: LuOutdent,
};
